version: '3.4'

services:
  catalogdb:
    image: postgres

  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile  # Ensure this is pointing to the correct Dockerfile
    container_name: catalogapi
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - catalogdb
volumes:
  postgres_catalog:
